#+options: toc:nil
#+BEGIN_EXPORT html
---
title: 療癒，世界觀的擴展與改變
revise: 2017-09-05
---
#+END_EXPORT

* 序

  這篇文章的出現，對我自己來說也像個奇蹟，他是許多人共同付出的結果，我特別感謝那些願意把自己的生命分享給我的受訪者，要一個人坦露自己已經不容易，更何況這個赤裸裸的呈現，就將要被一個自稱為科學家的人，給無情的分析，誠如威廉．詹姆士曾說過的一個比喻，若一隻青蛙被生物學家給分類時，牠一定也會氣得跳出來抗議，我就是我，不是什麼兩棲類動物。

  由於這些受訪者無私的分享，並接觸了許多傳統教科書中未曾出現的知識與經歷，漸漸的讓這篇文章的原型在我心靈中閃現，原來這世界的一切知識都只是一個個被信以為真的假設與想法，而這些假設，竟然可以直接影響到經驗世界的樣貌與內容，也因此，一個生病的人為何會好，關鍵就不是一般的醫學理論所指導的那樣，而是得活生生的回到這個生病的人身上去看，看這許許多多的假設如何在病人自己的身上、在自己的生命經驗中作用，進而產生各種不同的結果，當然，也包括了大家所謂的奇蹟。

  我把這些假設現有知識的集合稱為世界觀，即使如此，我還抓不太到他是如何存在，如何運作，但他總是能夠觸動我的心絃，讓我不禁想要繼續往他帶給我的各種靈感和經驗中，不斷的找尋下去。

  接著，我想要感謝我的指導老師王孫崇老師，他的支持對我造成無比的影響，對於身處醫學學科的研究領域中，進行這一類的研究是不容易的，除了沒有相對的資源之外，他本身的議題，就受到該學科大大的排斥，然而，科學的本意是知識，而對知識的追求，正是對真理的一種嚮往與渴望。任何的學科都沒有理由因為找不到現成的研究框架或是該研究內容似乎是目前無法研究的題材就將之拒之門外，生命不只是一堆生化反應和電位差的變位，生命是每一個人的一切，比這所有的知識都還大。

  最後，我想謝謝那些支持著我進行這個研究的許多人們，而我特要感謝我的妻子，她除了幫我收集材料，與我討論分享我的知識外，更為我帶來許多和藝術相關的題材，而那些題材，拓展了我的視野，更讓我發現理性所推演出來的知識，也不過是所有知識裡的冰山一角，她在生活中各個層面的支持，更是我難以用言語就可以簡單的述說清楚的，因此，在某種程度上，她也是本文的作者之一。

  這篇文章，並不是一個已完成的作品，更確切的說，他不過才剛丟出一個問題，等著我繼續不斷的向裡頭去鑽研，然而，我卻等不及把他拿出來分享給所有對他有興趣的人，或是任何被他所觸動的人，我真誠的將他獻給那些欣賞這篇文章的人，他的存在是屬於每個閱讀並熱愛他的人，他會以適當的樣貌，活靈活現的呈現在不同讀者的心中。

  對於這一切，我只能讚嘆，感激的看著他的變化，而沒有任何的話可以說了。
