#+options: toc:nil
#+BEGIN_EXPORT html
---
title: 來自康復者的啟示
revise: 2017-09-05
---
#+END_EXPORT

* 來自康復者的啟示

  2014 年，我試著暫時放下以分子生物學的角度來看待癌症的研究，反而選了一條比較像是人類學家或精神科學家的方法，藉由親身的調查與訪問[fn:1]，去向那些從癌症中康復的人學習，試著解開癌症這疾病的神祕面紗。

  我訪問的第一個癌症康復者，是個卵巢癌末期的患者，然而，在沒有接受任何治療的情況下，才半年，就已經無藥而癒。當我見到她時，我甚至覺得她的健康狀態比我還要好，她的醫生這麼說，「奇蹟，我行醫三十年，還沒有見過像妳這樣子的案例，卵巢上的腫瘤已經完全消失了，連受損的腎也回復了正常功能，無論妳用的是什麼方法，請繼續做下去。」

  2014 年年中，我在 youtube 上看到一個從癌症起死回生的故事，我也買了那本書回來看[fn:2]，2006 年的時候，作者正因癌症躺在醫院的病床上，醫生已經做了死亡的宣判，可是在經歷了瀕死經驗後，她奇蹟似的活了過來，並迅速的回復了康復。從此他開始到處演講，分享他的經驗，願人人都能脫離癌症的恐懼與痛苦。

  2015 年，我無意看到了台大數學系的教授黃武雄親筆寫下的記事[fn:3]，二十年前，他得了肝癌，前往加州大學舊金山附屬醫院求醫，而同時，他寫了一封信詢問他在台灣最信任的醫生，「你很了解我的病情，也擁有最尖端的醫學判斷，如果你是我，而非我的醫生，你會怎麼辦？」他的醫生回答他，「我會回來與小孩及自己所愛的人一起度過最後的這段時光。」就這樣子，二十年過去了，又一位無藥而癒的案例。

  這些案例的存在，就醫學研究來說，是極為罕見的，醫學上把這一類的案例稱為自發性緩解(Spontaneous remission)[fn:4]。因為研究上的限制，這樣子的研究並不多見，多數以案例報導的方式來發表。原因之一，是因為我們無法從一個康復者的身上採集到任何癌細胞，就算採到了，我們也無從得知，整個過程中，癌細胞究竟發生了什麼事。多數人把這類的故事視為為奇蹟，把他們視為特殊案例。然而，身為一個研究者，我反而覺得這是一個非常有趣的題材，就像芭芭拉．麥克林托克所認為的，「一個獨特的個體並不代表是異類，而是他含有被忽略的特性。」而這些特性，值得被研究與解答[fn:5]。

** 第一個受訪者
   會遇到這個朋友，完全是一件意外，那時，我的家人得了癌症，癌症的魔力，完全抓住了我們的心，因為經歷過，才深有體會，癌症病人和家屬所面對的，不單單只是一個疾病這麼單純。對患者來說，癌症幾乎等於絕症，得到醫學的診斷，就好像拿到一張天國的就學申請書，想丟又丟不掉，而醫療方式的選擇也形成另一種無法言喻的負擔，人們幾乎沒有太多的方法可選擇，是要開刀獻祭身上的一個器官並同時面對開刀的種種風險，還是要接受放療並同時準備處理那可能無法逆轉的後遺症？如果化療讓人虛弱不已，到底又該怎麼辦，然而，就算把這些療法都做了，真的就能回復健康嗎？

   那時，我陪著親人在醫院看診，由於情況不太樂觀，醫生就事先把家屬給支到旁邊來討論，他想了解我們的想法，到底要不要讓病人知道檢查的所有結果，在討論之後，我們雙方都覺得病人有知的權利，也只有知道自己的狀況，自己才能為自己做出真正選擇，那對病人是有好處的。因此，醫生特地借了一間投影室，仔細的向我們報告所有的檢查結果。然而，我真的懷疑，如果沒有相當的醫學知識水平，有多少人能夠理解醫生的報告到底在說些什麼呢？如果聽不懂，那麼病人和家屬到底聽到了什麼？又想知道些什麼呢？報告的時間並不長，但病人卻從頭到尾不發一語，只是一臉凝重，靜靜的坐著，一股焦慮，硬生生的被壓在腳底下而無法表達。突然，病人說話了， 「醫生，吃了這個藥，我的病就會好嗎？」病人面色驚恐的問。 「我們得吃了一個療程才會知道。」醫生說。 「如果沒有效呢？」 「那麼我們得換藥，看你對那一種藥的反應比較好。」 「那如果換了藥還是沒有效呢？」 「我們還有第三種藥。」 「第三種藥有效嗎？」 「說老實話，我也不知道，但，依妳現在的狀況，能不能活到那時候，都還是個很大的挑戰。」醫生有點慌了，但也只能老實的回答。 一聽到這裡，病人臉立刻一沉，陷入黑色的精神風暴之中。

   回到家後，我們緊急開了會，病人向我提出了許多的問題，但繞來繞去，其實都是同樣的一個問題，「我現在該怎麼辦？」而同時，我也深刻的意識到，病人完全聽不懂醫生報告，對他來說，一切都太複雜了，也因為複雜，更增加了他內心許多的恐懼和不安，他只知道，自己身上長了個壞東西，狀況很不理想，治療的過程可能極為痛苦，更重要的是，沒有「特效藥」。然而，還能有其它的選擇嗎？看到親人那灰心喪志的神情，我非常的擔心，如果一個病人失去了對自己康健的信心，失去了希望，那麼治療這條路，就很難走下去了。因此，我做了一個決定，開始向朋友打聽，有沒有認識任何人是從癌症中康復的，如果有，能否讓我帶著我的家人，去見他一面，以建立病人的信心。

   兩天後，一個朋友和我說，他們知道一位從癌症康復的人，只是也從沒有見過他，但運氣還不錯，他們已經連絡到這個人了，而他也答應見我們一面，我聽了喜出望外。隔天，就驅車載著家人，一同前去訪問這個病友。也許我不該稱他為病友，因為他看起來比我還要健康。

   她是個卵巢癌末期的患者，經歷了六個月的蛻變，沒有進行任何的西醫治療，卻奇蹟地從癌症中康復，並且成為一位健康而充滿活力的人。醫師說，「妳的經歷已經打破了許多醫學的知識，妳的腎臟沒有醫治，竟然好轉，而且功能比之前還好，卵巢上的腫瘤已小於一公分，原本三高也都回復正常，無論是妳用了什麼方法，請保持下去，妳已經回復健康，不需要一直回診了。」

   當我第一次見到她時，她笑臉迎人，端了手巾給我擦手，同時還為我們做了一桌的素菜，是一個虔誠的一貫道修行人。連我都深深被她散發出來的能量給嚇到了，我心裡不禁嘀咕，這樣子的人，真的是個癌症患者嗎？

   過去的她，生活不正常，沉迷於賭博，幾乎日日夜夜以賭場為家，雖有信仰，但並沒有帶來多大的改變，更多的是兩種生活格格不入的衝突感。直到，癌症悄悄的找上門。

   當癌症被發現時，已經是末期了，身體多處都有轉移，體重足足掉二十公斤，幾乎無法進食，她奄奄一息的躺在醫院的病床上，忍受著各種檢查的痛苦。一次，醫生正準備為她做大腸鏡的檢查，她忍著痛苦從病床上爬起，但卻因為體力不支，踉蹌了幾步就跪倒在地了。她不禁痛哭，真心地懺悔。

   「請問，懺悔是什麼感覺？是悔恨嗎？是罪惡感嗎？」我問。 「不，是一種寧靜，是一種力量。」她回答。 「妳經歷到什麼？」我問。 「我見到了神，我想要成為一位為人奉獻的人，為我的宗教做見證，過去的一切都已經過去。我看到了我未來的生命。」他回答。

   從那時起，她拒絕了所有的檢查和治療，但在家人的堅持下，她定期兩個星期會回診去抽血，檢查癌指數，讓孝順的子女們安心。接下來的六個月，她留在家裡休養，她的兒子和她說，從網路上的資料看來，生機飲食對癌症很好，所以，她也自己試著做，如果有體力，就做做瑜伽。

   「可以聊聊你的生機飲食和瑜伽嗎？」我問。
   「對於吃方面，我很注重，因為世上有許多的人，他們在生產食物時，第一個念頭都是為了自己賺錢，並不會管這個東西對人好不好，第二個甚至第七第八個念頭，才有可能考慮到別人。所以，我盡量讓自己吃沒有任何加工的原始食材。至於怎麼吃，其實也沒有什麼特別的啦，我就到市場去隨意地買了一些蔬菜，回來洗一洗就打成汁，說真的，生機飲食真的太難吃了，但，我覺得這就像修行一樣，即然要戒口，我就不能吃我想要吃的東西。所以，每天都是以青菜水果，打成汁來喝。至於瑜伽，其實我也只是看著電視上的教學，跟著做而已。」她說。
   「嗯。」我認同的搭了一下話。
   「在最痛苦的時候，連站都有問題，常常為此哭泣，心裡錯綜複雜的感覺和思緒，加上幾年來聽道學來的道理，同時在自己身上發酵，那時我哭到跪下來，開始罵我自己，今天，我之所以會這麼的痛苦，都不是別人給我的，反而是我給人的痛苦還比這更多，在那一瞬間，心中不斷的慚悔，一股浩然之氣由然而生，突然感受到上天有一道光降下來，濟公老師跟我說，『徒兒啊，自己的業自己了。』當我看到濟公老師慈悲的神情，我就打起一股精神，說，『老師，放心，徒兒還撐得住。』」她繼續說。 「老實說，當我發現一切都沒得依靠時，那時，我能做的，就是依靠三寶。人施不上力的地方，就交給上天，依靠三寶。也奇怪，幾個月後，我的身體不但沒有惡化，還不斷的回復健康，我開始參加佛堂的活動，到了六個月後，我又回去回診，那時，我的所有指數都已經正常了。」她說。「一切都是上天的恩賜啦。」她笑了笑，並散發出一種極為溫暖的力量。

   這個訪問對我來說，別具意義，一方面，它讓我的家人看到了生命的希望，另一方面，也為我真正打開一條了解疾病和生命的道路，然而，我該怎麼去解讀發生在她身上的事呢？到底康復的關鍵是什麼？


** 初訪原始點基金會
   為了繼續研究癌症療癒，我進入了原始點基金會去訪問，那是幾年前一個中醫朋友告訴我的，但我卻從來沒有來這裡看過。我走進基金會的大門，試著和張釗漢醫師交談，看看能否合作一起做些研究，以幫助癌症患者。張醫師雖是個中醫師，卻不了解該如何用實證醫學的方法，讓自己的研究被學術界所接受，我們相談甚歡，不管如何，我們都有一個共同的目標，讓癌症不再是一個絕症。

   原始點療法，是中醫師張釗漢自創的一個醫療方法，起初，他是為了幫他罹癌的妻子，在疼痛上帶來些微的緩解，所以不斷的在妻子的身體上摸索按壓，當他發現了某處疼痛，竟然可以藉由另一處的按推而得到緩解時，他大感震驚，於是他拿起筆，記下了每一次按壓的結果。當時，他還是一個中醫生，每次下診時，他就把那些身上患有疼痛的人留下來，試驗他在妻子身上發現的結果，而許多人的疼痛，也因此得到了很大的改善。於是，他心想，或許「任何的疼痛，都在他處有一個固定的起源點，只要在起源點做適當的處理，疼痛就會消失。」從此，張釗漢醫師踏上了尋找這些原始痛點的漫長征途，藉由五六年不斷的在病人身上摸索，他終於把他的的結論給整理出來，也就是現今的原始點療法[fn:6]。

   基金會固定會在每個星期四的下午，與辦重症座談會，這天下午，會安排讓許多重症的患者前來向張醫師諮詢自己的狀況，而張醫師會在場為大家解答如何應用原始點療法，幫助自己的身體進行自我療癒，當時的我非常的興奮，因為我的眼前，居然坐著四、五位從癌症中康復的患者，他們現在都在基金會裡當志工，分享他們的生命故事，幫助患者如何進行自我療癒的工作。我一邊看著他們服務別人，一邊聽著張醫師的講述，然而，我的目光，卻總是會被那些受苦的患者給吸引，我想聽他們的故事，想給他們希望，讓他們有路可走。

   幾次座談下來，我發現患者的主訴，大概可以分為兩種，一種是對自己身體狀態的不確定感而引發的焦慮與恐懼，而另一類則受困於苦楚的症狀中而無法自拔的人。第一類人需要答案，需要希望，而第二類人需要一些方法來真的緩解他們的痛苦，不然，他們根本就不可能把他們的注意力稍稍的從這個個痛苦中移開，走向其它的可能。然而，我卻完全沒有辦法提供他們任何想要的答案。於是，我帶著這兩個問題，繼續前進，我開始了我的訪談工作，不只訪談那些因原始點而康康復的人，也試著去了解整個基金會所傳達的醫療思想與運作情形。

   在深入的了解了原始點療法的理論後，我的內心卻因為出現在我眼前的許多矛盾現象，而感到十分的困惑，例如，原始點療法為是反對生機飲食的，張釗漢醫師說，「有一些重大疾病的患者，都會去吃生冷的食物，例如水果，他們認為沒有煮過的這些食物，有更多的維生素，所以鼓勵大家要吃水果或是生冷的疏菜，很多人相信了，都開始使用生機飲食。當時，我太太罹癌的時候，我也試過生機飲食，生機飲食一方便價格更高，但我太太吃了也一樣不舒服。基金會有一個患者，吃了七年多的生機飲食，身體寒涼，結果去醫院檢查出癌症。很多人不了解寒涼傷人的概念，他們不知道許多疾病的病因就是寒涼，平常吃的時候感覺很好，可是一旦身體的平衡出了問題，要改變就很困難了。」

   然而，第一個受我訪問的朋友，不正是食用了生機食飲嗎？這中間是不是有什麼祕密被我忽略了呢？我想知道答案，我花了許多的時間待在圖書館和書局，尋找許多替代療法和食療的資料，那時，我才驚覺，原來有這麼多的療法可以選擇，有那麼多的飲食建議可以供我們做參考，但問題是，不論那一種療法，都有人無效，也都有人受益，那麼，到底該選擇那一個？那一個才有效？

* Footnotes

[fn:1] 截至目前為止，我們共訪問了九位從癌症中康復的人，我們可以從下表中得到簡單的資訊:
#+BEGIN_QUOTE

#+ATTR_HTML: :border 2 :rules all :frame border
| 受訪者編號 | 癌症與分期                 | 性別 | 現今年齡 | 已存活時間  |                     使用療法 |
|------------+----------------------------+------+----------+-------------+------------------------------|
| /          | <                          | <    | <        | <           |                            < |
| <c>        | <c>                        | <c>  | <c>      | <c>         |                          <r> |
| 1          | 卵巢癌末期                 | 女性 | 63       | 6年         |                         宗教 |
| 2          | 卵巢癌末期                 | 女性 | 63       | 9年         | 主流醫學、宗教、瑜伽、原始點 |
| 3          | 乳癌二期(二十年前分類法)   | 女性 | 71       | 20年+       |           主流醫學、生機飲食 |
| 4          | 大腸癌三期                 | 男性 | 64       | 7年         |             主流醫學、原始點 |
| 5          | 乳癌末期(二十年前分類法)   | 女性 | 74       | 20年+       |                   宗教、瑜伽 |
| 6          | 大腸癌初期(治療中轉為三期) | 女性 | 38       | 第3年       |                     主流醫學 |
| 7          | 二十年前乳癌初期後複發     | 女性 | 57       | 20年+       |         主流醫學、氣功、靜坐 |
| 8          | 前列腺癌末期               | 男性 | 60       | 3年，已過逝 |                 多種替代療法 |
| 9          | 乳癌一期                   | 女性 | 50       | 7年         |   主流醫學、心靈課程、原始點 |
| 10         | 急性淋巴白血病             | 女性 | 60       | 4年         |               主流醫學、宗教 |
|------------+----------------------------+------+----------+-------------+------------------------------|

其中，癌症與分期這個欄位，是由受訪者口述當時醫生診斷的結果，然而，二十年來，對於癌症的分類，有多次的更新，由於許多受訪者存活已超過二十年，只得記錄口述結果。而使用療法這個欄位，並不等同於醫學所定義的療法，只是將受訪者在生病期間所進行的各種嘗試與方法，進行歸類後整理出來的列表。
#+END_QUOTE

[fn:2] 艾妮塔．穆札尼，《死過一次才學會愛》，橡實文化，2013

[fn:3] http://www.tmitrail.org.tw/whunag/?p=709

[fn:4] https://en.wikipedia.org/wiki/Spontaneous_remission

[fn:5] 羅傑．瓊斯，《衝擊，改變世界的物理概念》，正中書局，1997，頁342

[fn:6] 關於原始點療法的詳細資料，請見 http://cch-foundation.org/
