#+options: toc:nil
#+BEGIN_EXPORT html
---
title: 科學的本質
revise: 2017-09-05
---
#+END_EXPORT

* 科學的本質

** 直銷上的見證
   2016 年 10 月 5 日，我為了更深入的理解為何醫療有效的想法，我決定去參觀一家直銷團體的餐會，那是我之前訪問過的一位癌症病友介紹的，他覺得他服用了該產品後，身體獲得了許多的改善。[fn:1]

   用餐結束後，他們開始有人上台介紹產品，是一個和幹細胞有關的產品，依我生物資訊的背景，我輕而易舉的就能聽出他在解釋幹細胞時帶有多少荒唐與不可相信的見解，若把他的解釋放到醫學科學的領域中來解釋，這個藥是絕對絕對不會有效的。然而，居然有一群人因為這個產品而獲得療效。

   第一個上台見證的人，她是個六十歲左右的婦女，她患有一種罕見疾病，硬皮病，該病是一種全身性自身免疫病，發病時全身的皮膚會變的非常的硬，甚至會影響到內臟。這個病目前沒有有效的治療法，他們為了治療自己，試了中醫和各種的偏方，都效果都非常有限，到後來，自己只能坐在輪椅上，也幾乎不能進食了。後來，他們吃了這個產品後，身體開始改善，原本只能坐輪椅的她，居然已經能起身活動，還能飛到新加坡參加表揚大會。

   第二個上台分享的，是一個 64 歲的大姐，身體一直受到 B 型肝炎和 C 型肝炎的折磨，甚至已經開始發生肝硬化的現象，然後，在服用了一陣子這個產品後，他的肝炎居然產生了抗體，肝炎完全康復，他為了取信大眾，還當場亮出他去醫院檢查的單據，他的肝炎確實完全的消失了。

   第三位分享的人，約四十來歲，在該公司的身份地位應該比其它的人都還要高，他會服用這個產品，是因為他就要接受洗腎了，但現在的他，身體強健，充滿活力。

   餐會後，我為了得到更多的資訊，就陪著我的朋友，陪同另一上台見證的肝炎的朋友一起回家，我抓住機會訪問了他， 「為什麼之前吃了那麼多不同的直銷的產品，卻在這裡找到了希望？」我巧妙的問。 「之前不同的直銷團體，所提供的環境，都很不好，有許多都賺不到錢，只是無止盡的屯貨賠錢，但在這家公司，並沒有這樣子的事，我很崇拜這家公司的老闆，他的風采和慈悲心，都讓我心生景仰，我希望有一天，也可以爬到更高的位置。」他神采奕奕的回答。並和我分享了很多其它朋友的見證，有人因為父親吃了有效，而全心的投入這個事業，當然，也有一些人，完全是因為事業上的不成功，而投入這個企業，他熱心的想要為我介紹更多的人給我研究，並大概的和我介紹這些人的狀況，也因為我的背景是個研究人員，他們並沒有向我推銷各種的東西，反而更向是要向我證明他們的產品有多好，他們對我反應出來的態度，我可以很直覺的排除他們對我說謊的可能。

   有趣的是，當他在向我介紹這些病友的狀況時，著重在療效的部分並不多，更多的是他們如何在這個團體裡發光發熱的故事。那時我才驚覺，那個舞台才是他們真正需要的解藥，而然，要踏上這個舞台，藥必須有效，如果藥沒有效，一切都是空談，也因此，我注意到一個很有趣的現象：在這樣子的團體之中，多數回復良好的人，都是在這個組織中極為活躍的人，他們口才好，台風好，而直銷公直直接為他們打造了一個演出的的舞台，擴展了生命發展的其它可能。

   不久之後，我又去訪問了另一個直銷團體，或許又是因為我的身份的關系，她沒有向我介紹任何的產品，反而花了很多的時間向我介紹這個公司創辦人的理念是如何讓她感動。這幾次的訪問，完全動搖了我對科學的想法，我甚至在思考，科學會不會只是真實世界裡的一個視角，不是全部。

   一位我訪問過的受訪者，他有長期失眠的問題，醫生給他 Stilnox 10mg 的藥來幫助他的睡眠，然而，他卻像我抱怨，吃了藥之後，他又而一點也不想睡，他說，
   #+BEGIN_QUOTE
   「那天，我吃了兩顆藥，可是我的精神卻出奇的好，由於長期的失眠，使的我作息不正常，也很少運動，體力已經非常的弱了，可是那天，我竟然覺得自己的精神和體力，可以好到去跑操場，一開始，我並不太相信我的感覺，但最後我決定試一試，我換上了運動服，跑到附近的運動場的跑道上，我一圈一圈的跑，我整整跑了十圈，卻完全不會覺得疲累，這種感覺非常奇怪，我甚至一邊跑一邊笑，讚嘆那種身體健康的美好感覺。」
   #+END_QUOTE
   他的反應，與預期的藥效與副作用，完全不符[fn:2]。

   1962 年的一項實驗中，Jarriet Linton 和 Robert Langs 告訴一群受試者，他們將參與一項迷幻藥 LSD[fn:3]實驗，但事實上，受試者所服用的卻是安慰劑，在服藥半個小時之後，這些人開始經驗迷幻藥的症狀，例如失去控制，對存在的意義有深入的看法等等。這些安慰劑效應，持續了數小時之久[fn:4]。幾年後，哈佛心理學家 Richard Alpert 來到東方，尋找修行人來印證 LSD 經驗的真相，他找到了數名願意試這個藥的人，有趣的是，他得到許多不同的反應，有一個人說，感覺很好，但比靜坐差，另一個人則抱怨，這個藥讓他感到頭痛。最有趣的是一名住在喜馬拉雅山下的一名修行人，這個人已經超過 60 歲，最初，Richard 只想試試 50 至 70 微毫克(百萬分之一克)的劑量，但這個人想要試 305 微毫克的藥片，Richard 遲疑了一下，還是決定把藥給了他，但那個人覺得還是不夠，最後共吞下 915 微毫克，依標準而言，這是非常大量的藥。Richard 嚇呆了，心裡期待這個人開始雙手揮舞，像妖怪一般怪叫，但結果什麼事都沒有發生，他一直保持原狀，一如往常。LSD 顯然對他無效有僅有一點點的藥力[fn:5]。吃了安慰劑可能有效，而吃了真藥卻可能沒效，藥物的作用，似乎無法用科學的定義來加以解釋。

** 科學是什麼？

   那麼，科學是什麼，到底科學回答了什麼？ 在我大量的和許多從重症中康復的人談話後，他們對科學的理解和態度，以及發生在他們身上的事，正不斷的衝擊著我的原有的想法，由於沒有受到正規的科學訓練，所以大多數的人，會用自己的想法去理解這些科學的知識。他們喜歡引用科學研究結果，然而，他們的理解常常與我有很大的出入，而我發現，重點似乎不在科學家是怎麼樣子論述這些觀點的，而是這些觀點，如何被每個人，以真理的方式加以利用。

   所謂以真理的方式加以利用指的是，人們常常引用科學研究的結果來證明自己的某些觀點，科學研究的結果，彷彿成為一個聲明，一個證據，用來把某個特別想法的重量提升到一個讓人信服的高度。以致於這些研究結果，在不同人的世界裡，竟有完全不一樣的解釋。或許我跳出來大聲的駁斥他們的想法，聲明他們所抱持的那些想法，只是他們個人的解釋，並不符合真科學實事的運作，但那一點意義也沒有。

   當我們認識到某個事物的時候，例如一顆約五百克堅硬的石頭，「它是由祖母傳下來的綠色信物，帶著一股淡淡香味，永遠與耶穌的聖像，一同冰冷冷的靜置在家裡的壇城之上，象徵著祖靈與聖靈的直接臨在，與整個族落的生命力。」我們可以把這顆石頭的各種屬性都列下來，包括了長、寬、高、形狀、大小、動運狀態，硬度、溫度、顏色、味道、組成的成份、所處的位置，由何人留下來，在那個地方生產，他和祖母的聯結，和聖靈的聯結，和祖靈的聯結，和整個族落的連結…等。如果我們有心要列，他的屬性可能無法完整的用一張紙就全部列下來，而這些屬性，全是由我們的意識所羅列出來的，每個人都會有所不同，有趣的是，人們依照其背景的不同，對所有屬性的價值認定，就會有所不同。一個的科學家，可能會把長、寬、高等當成主要的屬性，而給予長、寬、高特別祟高的地位，他武斷地斷定，其它所有的資訊，是依附在這主要的屬性之上，因為，這個主要的性質是不會受到主觀的影響而獨立的存在，他是真實，是絕對的客觀的。對一個思念祖母的父親而言，就不是這麼一回事了，這顆石頭的第一屬性，就是與祖母的連結和情感，其它所有的屬性，都沒有辦法在任何一刻，超過該屬性所擁有的價值。對一個部落而言，與祖靈的聯結是最重要的屬性，而一個基督教的傳教士，則會認可耶穌的臨在，而非其它的屬性。

   什麼是客觀？愛因斯坦說，「藉由語言的溝通，不同觀察者能夠在某個程度上比較經驗，結果不同人對於某些感官知覺會彼此相應，而另一些感官知覺則無法建立這類相應。我們習慣將不同人感覺相同的事視為真實，也就是客觀。」[fn:6]，我無法確定愛因斯坦所說的感覺相同是如何定義的，但某種程度上，這是一種共識，要達到這個共識，就必須抱持著相同或類似的世界觀[fn:7]。也因此，客觀真實，在不同文化，不同時代，不同團體和不同的信仰下，都會有著很大的不同。從某個世界觀出發而發現的事物，不見得會存在另一個世界觀的世界裡，然而，用此來否定另一個世界觀所觀察到的現象，非常常見，卻不太明智。

   義大利數學家兼自然哲學家伽利略提到，「人們普遍都有感覺到熱的經驗，在主觀感覺的敘述裡，『這個茶壺是熱的』的說法並沒有錯，錯的是，人們誤以為熱是一個真實的情況，真實的屬性，真實的性質，熱真的存在於使我們感覺到溫暖的物質裡。」從伽利略的角度出發，熱是我們賦予物理的名詞，事實上它們只存在於人類自己的意識裡。這種把某一屬性拉高成為主要屬性，而把其它屬性認定為附加在主要屬性上的次要屬性是極其主觀與武斷的，甚至能認出那些屬性本身亦是如此，而唯一能主導我們這麼做的，就是我們所擁抱的世界觀，世界觀可能是一群想法的集合與我們現下所擁有的知識，它們彼此之間，並不一定總是相容的，有時可能是極為矛盾的，但卻同時代表了生活的不同面向，這些想法之所以能成為世界觀，是因為他們堅固的深植一個人的心中，而被當成一個不證自明的真理來看待，而常常逃過了我們意識的覺察。世界觀大致上界定了我們知覺內容，定義了我們的知識，並主導了我們如何去思考與行動。

   牛頓力學，曾是解釋這個世界的經典，直到相對論問世之後，他的理論地位才開始動搖，科學家宣稱，牛頓力學只是相對論的一個特例，然而，真能從相對論中推演出牛頓力學嗎？我們真的只需要在相對論上，加上一個 (v/c)2 << 1 的假設與限制，就能推論出牛頓力學嗎？若人們只看數學式子，或許這是可行的，然而，一旦仔細的去思考數學式子背後所表達的意義，我們就會發現，那根本就是不可能的事情。當我們開始進行這樣子的推演時，我們所使用參數的各種定義，是屬於相對論的範圍。例如，時間、空間、質量等概念，在兩個理論中所代表的意涵是絕然不同的。牛頓的理論中，質量具有恒定性，但愛因斯坦理論中的質量可轉變為能量，只有在相對速度很低的狀況下，這兩種質量才能以相同的方式來度量。即使如此，這兩者之間，仍然是不同的。在牛頓力學的世界觀裡，一輛戴貨的火車，無論是停在軌道上不動，或是以每小時六十公里的時速奔馳，或以每秒鐘十萬公里的速度飛入太空，它的質量都始終如一，但相對論卻斷言，運動中的物理的質量決不是恒定不變，而是隨速度增加的[fn:8]。一個會變的質量無法推導出一個不變的質量，那是根本定義上的不同。沿著相對論出發，質量永遠可以改變的，也只能得到相對論所能推導的範圍裡。

   如果，時空的定義，不是「沒有作用的」、「均質的」、「等方的」(isotropic, 即其物理性質不因位置的不同而有所改變)，那麼牛頓力學便不能成立，而這也是愛因斯坦發展想對論時，最大的一個挑戰。然而，一但要把相對論轉換成牛頓力學，對時空的定義就得完全的翻轉，這種世界觀的改變，沒有真的親身經歷兩種世界觀，並再從中跳出來看的人，是無法完全的了解的。也因此，有人或許會嘲笑那些堅持「時空是不能彎曲的」的人不夠聰明，所以才無法了解相對論在說什麼。然而，事實上，牛頓力學和相對論，確實代表著兩種完全不同的世界觀。一個牛頓力學的信徒不會問「一台火車以每秒鐘十萬公里的速度前進時質量是多少？」因為對他而言，這是一個連想都不會想到的問題，質量恒定的概念，已經根深蒂固的根植在每一個信仰者的心裡，在不同速度度之下物體的質量是恒定的概念，就像一個不證自明的真理一樣，不需要被討論。如果真有人提出這個問題，還可能因此被一群牛頓力學的信徒大聲的嘲笑。然而，對一個相對論的信徒而言，情況就完全不同了，這個問題在他的世界觀裡是一個可以被問、被解答的問題。世界觀不僅僅只是界定了人的知覺，也界定了人問思考的邊界。因此，海森堡才會說，「度量儀器是由觀察者所建造的。」又說，「我們所觀察的，並不是自然的本身，而是自然對我們尋問的方法所展露的面目。[fn:9]」

   再舉另一個例子，義大利數學家兼自然哲學家伽利略，將其新發明的天文望遠鏡對準太陽，發現了上面的黑點，而這些黑點，顯然是在太陽的表面，根據伽利略的報告，這些黑點的形狀不規則，每天的數量和透明度也都不同，經過伽利略的計算，這些黑點絕不是遠離太陽表面，就算不是貼近著太陽，也是隔著小到無法察覺的距離。太陽黑子的發現，直接與當時的世界觀產生衝突，當時的人認為，太陽是「無暇、完美」的，所以太陽表面不能出現黑子，然而，伽利略卻提出太陽和地球同樣不完美的理論，伽利略說，「認為太陽是個完美的天體，所以不相信黑點會存在其上的說法……根本是沒有根據的。只因為們認為太陽是『最純淨、最清澈的』，於是無論實際感受如何，總之太陽絕對沒有黑影，也絕沒有不純淨的地方。但是，呈現在我們面前的太陽明顯有部分的不純淨和黑點，為什麼不應該稱它為『有污點、不純淨的』呢」？伽利略正在挑戰當時的世界觀。

   然而，關於是否能看到太陽上的黑子，卻不是一件簡單事情。1611 年，伽利略前往羅馬，把多位頗具盛名的哲學家聚集在城門上，向他們展示自己的望遠鏡，站在這個制高點，這些哲學家透過望遠鏡看到皇宮裡面的貴族是如此清晰，即使隔著16義大利哩的距離，我們也可以細數每扇窗，甚至是最小的那一扇，在是在那個位置他們可以讀到三公里外的展覽室裡的文字，甚至可以看到字母之間的句點。可是，當把望遠鏡指向天空時，事情就沒有這麼簡單了。伽利略在發現木星的衛星後，許多許多享有盛譽的科學實作者來做見證，許多見證者承認，望遠鏡在看向地球上的事物時，運作的極好，但望向天體時，卻有點故障，其中一位與會人士寫到：「伽利略沒有任何成果，因為在場超過二十位仕紳，沒有人可以清楚看到新發現的衛星，只有一些視力極佳的人，在某種程度上被說服了而已。」[fn:10]

   為什麼這些學者會看不到？是因為偏見或是一種想要打壓伽利略的心理，使得他們雖然有看到，卻故意當成沒有看到呢，還是另有原因？

** 不同的視角，不同的世界觀，不同的世界
   為了了解伽利略看得到，而其它人卻看不到的這個現象，我們得深入更多的主題來探討，以期獲得一個可理解的解釋。我想先舉兩個語言學研究的例子來說明可能的一些情況。

   心理學家米勒，曾經做過一個實驗，他放了一捲錄音帶給受試者聽，裡頭是背景充滿了噪音的句子，並要他們正確的複述他們所聽到的。這些句子，有些是符合英文文法規則且有意義的，有些就是把片語中的語詞打散，變成一些合乎文法卻沒有意義的句子，有一些是把片語結構打散，但是把相關的詞語放在一起，最後這是一些沒有意義也沒有文法的句子，完全不知道他是說些什麼。而實驗結果發現，合乎文法且有意義的句子，受試者重複的結果最好，其次是合乎文法但無意義的句子，再其次是不合文法的句子，最糟的是不合文法的胡扯。幾年後，心理學家華倫，錄了一些句子，例如: the state governors met with their respective legislatures convening in the capital city. 他把 legislatures 這個字的第一個 s 換成一個咳嗽的聲音，在播放給受試者聽，受試者完全沒有察覺任何一個聲音的消失 [fn:11] 。這個些實驗的結果，造成許多人強烈的反彈，似乎這個實驗，證實了相對主義[fn:12]的哲學的觀點，也就是說，我們只聽到我們想要聽的話，我們的知識決定了我們的知覺。

   另一個例子，是發生在 2015 年的 2 月，網友 Swiked 在社交網站 Tumblr 上貼出一件洋裝照片，意外地讓無數人陷入「顏色爭論」之中，隨著各大討論區和網站紛紛轉貼此圖，很快消息傳播到世界各個角落。說到這件洋裝的顏色，一派人堅持是「白金色」，另一派人主張是「藍黑色」，還有網友表示，一開始看是「白金色」，隔了一陣子再看就變成「藍黑色」。更有人說，用不同電腦、不同螢幕看，會有完全不同的視覺效果。為了解決爭議，國外知名網站《BuzzFeed》做出了網路民調，吸引超過 200 萬人投票，共有 140 萬人、約 72% 支持「白金色」，55 萬人、約 28% 支持「藍黑色」。德國吉森大學的 Karl R. Gegenfurtner 與他的同事，研究並記錄一群人看到那件洋裝的情況，他們發現，其實不只有兩個可能的色彩組合，有些人會在這張影像上讀到更多的色彩連續體，有些人看到白金色，黑藍色，也有人看到比較粉色的組合[fn:13]。這顯示，每一個人看到的顏色，可能都不一樣。

   我們不是看著同樣的一個物體嗎？為什麼不同人會看到不同的顏色？有科學家認為，這是人們的視覺，會彌補燈光的差異，以此評估物品真正顏色。也就是說，當人們看到白金色的原因是，他們認為洋裝處於燈光昏暗的環境，所以藍色調的顏色應該被解釋成陰影，而看到黑藍色的人則認為，背景的燈光是明亮的，因此黑藍色是正確的顏色[fn:14]。這樣子的解釋，並沒有完全的回答那些看到粉色系的人是怎麼一回事，然而，卻為我們帶來一個更大的線索。我們的知識，決定了我們到底該看到什麼樣子的顏色。

   Bruner 和 Postman 做了一個實驗，他們讓讓受試者辨識一系列撲克牌的花色，每一張牌在受試者眼前，只暴露很短的時間，並且實驗者可以控制時間的長短，這些牌中，有許多張都是正常牌，但有一些故意做成異常牌，例如，紅桃六、黑心四，實驗中每回讓一個受試者以各種不同的曝光時間看一張牌，曝光的時間由短而長，每次讓他看了牌之後，就問他看到什麼結果，連續兩次成功，這一回即結束。許多受試者都能利用時間中最短的撲克牌曝光時間，辨認出初大部分牌的花色，曝光時間稍微增加之後，全部的受試者都能只指認所有的牌，對正常的排，他們的辨認通常是正確，但是異常花色出現時，他們也幾乎毫不猶豫的將他們認為是正常的，例如「黑心 4」可能被認成「黑桃4」或「紅心4」，他們沒有察覺到任何的不對勁，那些怪牌立刻被歸入由過去的經驗所形成的觀念範疇之中。我們甚至不能說受試者看見的東西與他們辨識出的東西並不相同。要是把異常牌的曝光時間加長，受試者就會開始猶豫，表現出他也覺察到異常現象的樣子，例如，看到一張紅桃 6，有些受試者會說「這是黑桃 6，但卻有點怪怪的，黑桃卻有紅邊。」當異常牌曝光的時間再延長，受試者變更為遲疑，時間不斷的增加的結果是，到最後絕大多數受試者會毫不猶豫的說出正確的花色，例如紅桃六，有些受試者在認出了兩三張怪牌之後，他們就能輕易的辨別其他怪牌了。可是有好幾個受試者，就是沒有辦法，甚至當怪牌的曝光時間，增加到他們辨別正常胎平均所需時間的 40 倍之後，還有超過 10% 的怪牌被認錯，而且這個類沒有辦法認出異常牌的受試者，常會陷入深沉的沮喪之中，其中一個人說，「不管牌的花色是什麼玩意兒，我就是認不出來，它看起來根本就不像牌，現在我甚至不知它是什麼顏色，更不知他是黑桃還是紅心，現在我連黑桃是什麼形狀都搞不清楚了，我的天啊。」[fn:15]

   我不知道上述的這個實驗，是否能和伽利略把望遠鏡望天空請專家來見證的事件能否類比，伽利略確實和其它的專家看到了不一樣的東西，而樸克牌的實驗者和受試者，也確實看到了不同的東西，唯一不同的事，當時的伽利略並不是實驗者，他雖然試圖說服其它的專家，但他說的話沒有權威性，不足以動搖其它人的想法。然而，在樸克牌的實驗裡，實驗者是個「知道事實」的權威者，當他向受試者聲明，他看錯了花色時，受試者沒有立場反對，他們意識到了有別於他自己意識範圍之外的可能，有些人接受了，有些人遲疑了，有些人反而陷入兩個相法的衝突與困惑中，甚至連原本自己所看到的花色都認不出來了。

   這樣的解釋，不一定所有的人都會信服，人們仍然可以堅持，「難不成沒有一絕對客觀的撲克牌花色嗎？那個花色，絕不是只存在實驗者的知覺之中。」我並不完全反對這個論點，客觀是存在的，如果沒有客觀，我們主觀就沒有對像，主觀很自然也不存在了，然而，客觀的存在，卻不需要是絕對的，不需要是舉世皆同的，也不需要是獨立於主觀之外而存在的。這種心物二元的概念，我很想把它歸因於笛卡耳的哲學思想，某種程度，這個思想與後來的唯物論哲學，大大的影響了現代科學所抱持的世界觀，指導著科學家怎麼去看這個世界。就撲克牌實驗而言，實驗者拿了一個包含了異常牌的撲克牌(依他自己的認知)，並把它依照曝光時間的不同，呈現給受試者，不同的曝光時間，代表著不同的資訊量，不同的資訊量，就有可能帶來不同的知識而引起不同的知覺，而這個知覺完全取決於個人。那麼，那些科學家看不到伽利略看到的衛星，就不足為奇了。

   這裡，我想舉兩個訪談的例子，來說明我們的世界觀和所抱持的知識，如何影響著我們經驗到的世界。主角是名一貫道的道親，我是從他的先生那裡，訪問到她的故事，
   #+BEGIN_QUOTE
   我是跟著我太太吃素的，我會開始吃素，也是因為發生在我太太的事讓我感到驚訝，他可以完全的感覺到食物是否是不潔的，只要他一沾到不潔的食物，他就會反胃身體不舒服。這個過程，並不是突然發生的，是一個漸進的過程，剛開始的時候，她只是開始清口(一貫道術語，指開始茹素)，但漸漸的，他可以感覺出食物中是否有混到暈食的存在，而且其敏感程度，讓我非常的震驚。有一次，我買了一家公司的餅，餅的包裝標示著素食兩個字，可是我拿回家給我太太吃了吃了以後，她就跟我說說這個餅裡面有不潔的東西，身體不舒服，我心想，這是真的嗎？就打去食品公司詢問，最後，他們的經理和我說，這個食物確實在制作的過程中，混了一些葷食，我很不開心，覺得他們這樣子根本是欺騙消費者，所以就要求他們改善。這些故事太多了，多到我都說不完了。然而我太太的這個特質，並不是一開始就這麼的敏銳，而是漸漸活化起來的，到後來，她甚至可以感覺到更細微的狀況。那是我爸爸過世的時候，當時，我們很忙，常常買外食，可是很奇怪的是，只要食物是經過我的手，我太太吃了就會不舒服，這點讓我驚訝不已，我為了實驗，就請我一個朋友幫我去買一個我指定的食物，結果我太太吃了就沒事，也就是說，他到後來，已經能夠完全的區別任何不潔的食物了。」
   #+END_QUOTE

   另一個故事，是一名從癌症中康復的好友，他們全家都一致的認為，食物是媽媽致病的真正病因，因此，全家都力行李秋涼小姐推行的生機飲食，他的先生說，
   #+BEGIN_QUOTE
   她自從生病後，她的身體就變得愈來愈敏感，一沾到不潔的食物，身體就會有很大的反應。好歹我也是台大哲學系畢業的知識份子，總得有些實驗的精神，所以我就偷偷做了幾次的實驗。一次，我在燙青菜中，加入了一般市面上的油，他才剛拿起盤子，就放了下來，說這個食物不對勁，他不想吃，那時我真嚇了一跳，他是怎麼樣子發現的，後來我又做了好幾次的測試，通通都得到一樣的結果，他的身體對食物的反應非常的大，甚至只要經過大學部的食堂，就噁心的快要吐出來。
   #+END_QUOTE

   這兩個訪談的主角，都對「不潔」的食物都有極為敏銳的敏感度，可是他們對不潔的定義卻是不同的，一個是宗教定義上的不潔，一個是無毒與否的不潔，而兩個人的感官，卻又天衣無縫的和自己的信仰與知識相結合。

   人類學家 Turnbull 曾經在剛果枝葉茂密熱帶森林中，研究俾格米人的生活方式，他描述過下面的一個實例：有些俾格米人從來沒有離開過森林，沒有見過開闊的視野。當 Turnbull 帶著一位名叫 Kenge 的俾格米人第一次離開居住地大森林來到一片高原時，他看見遠處的一群水牛，驚奇地問，「那些是什麼蟲子？」Turnbull 當告訴他是野牛時，他笑了出來，以為 Turnbull 是在開玩笑，並再一次詢問那是什麼蟲子並喃喃的嘀咕著，「我這位朋友也太不聰明了，怎麼會拿野牛去比甲蟲呢？」Trunbull 立刻開著車子，和 Kenge 一起接近這些野牛，當 Kenge 著看動物的體形不斷的變大時，他小聲說，這可能是魔法，最後，當他們來到野牛旁，看到野牛真實的大小時，他仍然懷疑它不是不是在剛剛那段開車的時間裡長大大，或是有人在這裡頭耍花招。當兩個人繼續開車來到湖邊的時候，發生了類似的情況，這是一個很大的湖，在兩三英里外有一艘魚船，Kenge 不肯相信幾英哩外的那條船可以裝下幾個人，他斷言那不過是一塊木頭，直到 Turnbull 提醒他剛剛野牛的經驗後，他才點了點頭表示同意。回到森林前的日子裡，Kenge 觀察遠處的動物，並試著猜測他們是什麼，他正不斷的讓自己適應新的知覺訊息[fn:16]。」

   這些例子已經夠多了，由此，我們至少能夠稍稍的抓到一個概念，一個人的世界觀是如何影響並形塑著自己所經驗的世界。

* Footnotes

[fn:1] 關於直銷帶來的療癒的研究，仍然在進行當中，未來會有更多的資料與研究呈現。

[fn:2] 根據三軍總醫院臨床藥學部所提供的 stilnox 藥物彷單，該藥物的主要作用為治療失眠，而可能的副作用為頭暈、頭痛、嗜睡、噁心、過敏、腹瀉或便秘、視力模糊或產生幻覺。

[fn:3] D-麥角酸二乙胺（Lysergic acid diethylamide），也稱為「麥角二乙醯胺」，常簡稱為「LSD」，是一種強烈的半人工致幻劑。

[fn:4] Hurley, Investigations, p.10

[fn:5] Richard Alpert, Be Here and Now (San Cristobal, N.M: Lama fundation, 1971)

[fn:6] 愛因思坦，《相對論的意義》，台灣商務，2005，頁1。

[fn:7] 世界觀，在文章中可能有不同的等義詞，諸如，人生觀、宇宙觀。在在這三個詞是之不斷的切換，是為了保持書寫時的流暢性，而非他們擁有不同的意義。世界觀是一群思想的集合與我們現下所擁有的知識，這些思想與知識彼此之間，並不一定總是相容的，有時可能是極為矛盾的，但卻同時代表了生活的不同面向，這些想法之所以能成為世界觀，是因為他們堅固的深植一個人的心中，而被當成一個不證自明的真理來看待，而沒有絲毫的懷疑。世界觀是一個開放的動態系統，裡面的思想，並不是永遠不會改變的，許多不適合自己發展的想法會在生命的不同過程中被丟棄，同樣的，也會有新的想法開始被建立起來，成為世界觀的一份子。用個更簡單的話來說，一個人的世界觀，除了現下所擁有的知識外，他主要包含了下面幾個面向的想法，自己是什麼，世界是什麼，人與世界的觀系，人與自然的關系，人與形而上或者說是神的關系。

[fn:8] 孔恩，《科學革命的結構》，遠流，1994，頁154-155

[fn:9] Werner Heisenberg，《物理與哲學》，幼獅文化事業公司，1987，頁45

[fn:10] 史蒂文．謝平，《科學革命》，左岸文化，2016，頁106-108

[fn:11] 史迪芬．平克，《語言本能》，商周出版，2015，頁227-229

[fn:12] 知識的相對主義者主張知識的內容會相對於不同的情境而產生變化。

[fn:13] Gegenfurtner, K. R., Bloj, M., & Toscani, M. (2015). The many colours of ‘the dress.' Current Biology, 25, R543–R544

[fn:14] 茱莉亞．蕭，《記憶如何對你說謊》，商周出版，2016，頁45-47

[fn:15] 孔恩，《科學革命的結構》，遠流，1994，頁113-114

[fn:16] Roger R. Hock，《改變心理學的 40 項研究》，北京：中國輕工業出版社，2004，頁50-52
