#+options: toc:nil
#+BEGIN_EXPORT html
---
title: 療癒，世界觀的擴展與改變
revise: 2017-09-05
permalink: /worldview/一個新的假設
previous: 科學的本質
next: 癌症不是絕症
---
#+END_EXPORT

* 療癒，一個新的假設

** 醫療即是儀式
#+BEGIN_EXPORT html
<a id="org001"></a>
#+END_EXPORT

   即然，我們已經知道醫學科學只是某個世界觀所代表的視角，那麼，要回答許多不同替代療法，宗教療癒以及自發性的療癒，我們就得先丟掉所有的醫療理論的外衣，暫時放下該理論背後的知識和世界觀，我們才有可能得到一個更加清晰的畫面，以致於了解生命這個了不起的奧祕。

   想像一下我們的醫療程過與場景，地點發生在醫院，一個象徵著醫學權威與知識的聖殿，病人們來到這裡向裡面的專業人員求助，這些專業人員，擁有身體所有的知識，當病人向醫生說完所有的病症之後，醫生開始進行可能的疹查和治療，醫生可能會量你的心跳，摸摸你的肚子，用聽器從你的背後聽著你的呼吸，最後開了一些藥，並說了一些生活上注意的事項，病人就回家了，沒有多久，病人的病就好了。

   這是一個大概的場景，我想每個人多少都經歷過。現在，讓我用另一個我在台北某道壇實地觀察得到的一個記錄來對比，那個道壇空間不大，神桌上奉祀著許多神明，雖然我從小在道教的環境裡長大，但我還是沒有辦法回答出壇中的主神究竟是那一位。這天，許多帶有病痛的人，都來到這裡求診，希望身體的狀況能夠獲得改善。當輪到患者的時候，患者先是向神明上香，然後向坐在神桌旁的一位師父說明自己的狀況，這個師父聽完之後，口中拿拿有詞，由於聲音很小，所以我沒有辦法聽清楚他在說什麼，他說完之後，就拿起筆，寫下一些東西，並交給旁邊的執事人員，執事人員看了看，就把患者帶到旁邊，請病人坐下，然後開始在患者的身上，做一些非常類似刮砂的動作，然後再交給患者一碗符水，要患者喝下去。整個治療就這樣子完成了。那時，我是跟著一位服用精神藥物的朋友一同前往的，他在看完病之後，原本昏沉的意識突然就這樣子清醒了，他大叫，「我好久沒有這種感覺，之前我的腦袋好像被什麼東西堵住，沒有辦法思考，可是現在我回復清醒了。」

   下一個場景，是中古歐洲修道院的治病的情景，當然我沒有辦法坐時光機回到那個時代，所以以下的資料，是由一個在希臘阿索斯聖山1隱修了二十年的神父告訴我的。古時候並沒有醫院，教會就是醫院，當人們來到教會求助時，神父會仔細的聆聽病人的狀況，之後請患者告解，並為之祈禱，他們會在患者的頭上敷上聖油，並給他們一些香料，整個醫療大概就是這樣子進行的。

   我故意刪掉了一些關於科學、神學和宗教學的解釋，只是還原出現場大概的狀況，只要我們不要受到「理論」的迷惑，我們很明顯的看出，宗教療癒的現象，與醫院之間，是多麼的相似。兩者都會有一個權威者來進行必要的儀式，神職人員為需要為信徒獻祭(或祈禱)，說著神靈如何運作的神話故事，而醫生則必須診療，並說明在醫學科學研究上，這個病運作的機制。而兩者背後都有一個信仰的主神，祭司和信徒信仰的是上帝或其它的神靈，而醫生和患者信仰的是科學。祭司和信徒都沒有辦法把上帝的概念做完整且精確的論述，而醫生和患者，也同樣不太了解什麼是科學。一場接一場有趣的「醫療儀式」就這樣子上演了。因此，療癒的發生，或許和理論並沒有太大的關系，理論所提供的，是對一個世界觀強而有力的聲明，一個大到讓所有人都信服的聲明。

   做這種類比，許多人，特別是醫生，可能會認為相當的不倫不類，竟然把神祕主義甚至是坊間的迷信帶進科學的殿堂來，從某個角度來說，這種想法是極其不公平的，當人們武斷的把某些物質屬性定義為主觀的、不可靠的，或是神祕的的同時，我們就失去了延著那條屬性去看世界的可能性。讓我們再看幾個訪問的例子，再回來繼續我們的討論。受訪者是兩位從事能量舞教學的覺知舞者以及一名中醫師的分享。

   以下是第一個舞者的自述，
   #+BEGIN_QUOTE
   我從小就對人就敏感……常常安靜的在觀察人，年輕的時候就對宗教非常的有興趣，喜歡待在佛堂裡，喜歡在裡頭感受那裡的頻率，也在一貫道待了將近十多年的時間。過程中，曾試著進入一貫道的核心去工作，擔任全省巡迴的講師，可是一進入到核心工作之後，卻發現到許多人事上的問題，大家的注意力都在辦道上面，而忘了去修習自己的心，甚至許多人還因為過度勞累，連身體都搞壞了，那時，我曾經試著提出這些問題出來討論，但卻都無疾而終。也不知道為何，在那段期間，身體開始變得不一樣，彷彿打開了某種覺知，常打嗝，開始有預知的能力，可是這個感覺帶來的，卻是一種異常的恐懼，因為如果能預知讓自己可以完全的知道什麼事情會發生，那自己就能預防，可是，你知道嗎？面對這股未知的能量本身的那種未知感，才是最可怕的。有些人可能會因此走入神壇當乩童，但我一點也不想要這樣子，我開始學習許多心靈的課程，探索靈性的問題，研究什麼是能量。並開始研究自己的身體，漸漸的，我發現，身體的感覺是被情緒影響，而情緒又被我們的五識所影響。隨著自己的意識與身體的頻率不斷的提升，也慢慢的能夠從另一種角度，看得到人們身體裡面的痛苦，所以，自己才會投能量舞的研究與工作，試著直接以肢體的方式，將我們的感受，直接以能量的方式來釋放，而這是我一輩子在研究的，同時這也是我的使命。
   #+END_QUOTE

   再來看另一個舞者的自述，
   #+BEGIN_QUOTE
   在我 30 歲之後，身體和肩膀，常常感到異常嚴重的疼痛，幾乎看遍了中西醫，都沒有檢查出什麼太大的問題，也做了針灸復健，效果始終有限，無法治根。所以，為了治療自己，我就開始去學習瑜伽。在不到一個月的學習過程裡，我學會了把感知往內收攝，回到內在中脈，也在靜坐中打開了脈輪，身體也開始有了一些特別的變化和感應。但這樣強烈的能量，越來越大，讓我整天坐立難安，總覺得內在有一股能量快要爆衝出來，我去過宮廟，但我不想當乩童，我開始尋找平衡的方法，也因此發現了能量舞，在學習了這樣的舞蹈後，讓我學會了內在平衡的方法，這股能量，反而讓我在學習能量舞時，有許多的優勢。
   #+END_QUOTE

   一位中醫師朋友分享的故事，
   #+BEGIN_QUOTE
   有一次，我帶一位憂鬱的病人參加了一個印度新興教派的儀式。她在儀式中深受感動，還看到了每個人身上散發的氣場和光芒，從此開啟了一些特殊感官的能力。你知道她現在怎麼樣了嗎？他不在憂鬱了，她成為一名優秀的風水師。喔，我真為她感到驕傲！
   #+END_QUOTE

   先暫時不要會理這些事例背後的理論和可能的世界觀，單就他們的經驗來看，若是一個完全信仰主流科學和醫學的人，絕對難以順著這股感覺找到這樣子的視野，甚至可能會因為自己認知經驗的種種的變化而不斷的出入精神科的診間，而難以順著這個意識的變化，看到一個完全不同的世界。印度近代四大聖人之一的 Ramakrishna [fn:1]，他的三摩地經驗，被醫學唯物論者解釋為大腦不正常放電的癲癇患者，Saint Teresa [fn:2]是歇斯底里病患，Saint Francis [fn:3]是遺傳性的退化者，George Fox [fn:4]是大腸失調症侯群，Thomas Carlyle [fn:5]是十二指腸發炎[fn:6]。因此，用一種世界觀裡的成果，去衡量另一個世界觀所發展出來的成果，根本不可能的，他本身就是一種強大的偏見，除非我們改弦易轍，像俾格米人 Kenge 一樣，開始調整自己的世界觀，去認識那個全新的世界。

   如果大家能接受這個的觀點，那麼，許多替代療法，特別是各文化中的傳統醫學，就更容易被我們學習與理解，我們不會把針灸聯想成安慰劑[fn:7]，或著試圖在人類的身體，找到經絡的解剖學證據，更不會把氣功當成一種幻想的玄學，而陷入難以回答的爭論裡。一個知識背景和世界觀中完全沒有氣的概念的人，針灸卻實無法產生太多的療效，一個乏於利用嗅覺去認識這個世界的人，芳香療法也很難帶來什麼特別的效果，瑜伽和氣功，對一個信仰主流醫學的人，不過就只是個運動而以。人們只要沒有共識，永遠是雞同鴨講。

   一個我訪問過的老奶奶，今年已經 98 歲了，她從 20 歲結婚後，就一直住在同一個地方，這個地方十份的鄉下，科學在這裡的影響，大概就是透過收音機所帶來的那些似是而非的資訊。老奶奶很特別，他無論做任何的事情，都會向自家的供奉的王爺[fn:8]請教，如果沒有擲出聖筊，老奶奶是不會行動的，這種簡單的宗教生活，幾乎就是她生命的全部。幾次，老奶奶感冒生病，奶奶的兒子就要帶他到市中心去看醫生，但怎麼看都沒有用，老奶奶堅持要回家去找道士做法，並向王爺請安，兒子總覺得奶奶迷信，但怪的是，每次道士一做完法，奶奶的病就很快的好轉了。如果從這位老奶奶的世界觀出發，也許真正迷信的人，反而是我們這些受過高等教育的知識份子。

   讓我們把焦點放回醫療的現場，繼續討論「醫療儀式」的真正意涵。

   儀式的重點不在用了什麼祭品，或是使用了什麼醫療的手段，甚至是在那裡發生，儀式的重點在「溝通」，而「溝通」的目的，是要造成精神上的感動和改變，以擴展或創造新的世界觀，只要人們能夠在這場溝通中，從原本固著的情境中走出來，療癒自然就會發生。

   我們用嘴吧和別人溝通與交流，因此人們創造了語言，進一步，人們創造了圖象，創造了文字，然而，還有更多的溝通與交流，是沒有被我們的意識察覺到的，例如，肢體語言，情感語言，情緒語言。情境語言，超感官語言(如氣功，各種通靈)…等。因此，當一個醫療儀式進行時，如果我們真的想要了解療效何以發生，就得深入的去看這些不同的語言之間，是如何進行溝通，並把所謂疾病的情境帶往那個方向前進。

   我把醫院歸類在情境語言。醫院、醫生本身的象徵，就已經在第一時間在和患者的內在溝通了，這個象徵在告訴我們，這裡是一個專門治療疾病的神聖場所，所以，安心的自己的狀態交給醫院吧。因此，許多人常常病的東倒西歪的，一到醫院，病突然好了一半，看到醫生，就好了另一半，只剩下一些看似可有可無的症狀。當然，進入醫院之後，整體情境的反差造成不同的結果，我這裡就不說明了，我只試著提出一個大概的輪廓。

   當患者進入診間，開始和醫生進行接觸的時候，患者和醫護人員溝通，特別是醫生，就十分的重要，這時會出動的語言有，口語、肢體(除了醫生本身的肢體語言外，也包含了各種醫療行為)、情感、情緒、藥物、雙方的身份象徵…等，醫生會在他的大架構裡，和患者的各個部分溝通，告訴患者的每一個部分，如何回復健康。學過語言的人都知道，一組詞彙可能有很多種的意思，放在不同的文意下就有不同的意義，在治療的過程中也是，藥物及治療手法真正意思，也是由所有其它的部分所決定的。所以，藥物和治療手段對於是否真能康復的關系，就無法用單一的標準來衡量來了，因此，患者在接受了醫生的一整套的溝通後，聽到的是全語言(所有不同語言加總)的結果，在加上自己個人主觀的詮釋，一直到這時，藥物或治療手段可能帶來的結果，才被確定下來了。這也是為何不同的醫師開同樣的刀，效果會有如此大的差異，反過來，不同的人給相同的醫師開刀，一樣會有不同的效果。

   因此，我想用自己一個親身的經歷，來說明醫生是如何使用這些可利用的工具，來為一個患者，帶來真正的療癒。在我大學的時候，生了一次病，而且一病就是一個月，我到振興醫院看了好幾次，都沒有得到太多的效果，病懨懨的我，心裡突然閃出一個直覺，我想要回家去找我的家庭醫生，也許他對我最了解，可以真正的幫助我。於是，當天，我馬上就買了車票回家去找我的家庭醫生。診所裡的人不多，所以很快就輪到我看診了，醫生為我做了許多觸診，也利用了一些儀器和化學檢驗來檢查我的狀況，醫生問了我一些生活上的問題後，突然把手上的聽診器和筆放下，用一種充滿慈愛的眼神看著我：「我從來沒有幫你打過點滴吧，下午過來，我幫你打針，明天就沒事了。」我被醫生的神情打動了，不知不覺卻笑了出來，馬上點頭答應，鑑午過來接受治療。兩天後，我就從那個糾纏了我快一個月的疾病中走了出來。從我現在的角度來看那一次的治療，真的是別具意義，首先，這個老派的醫生，仍然熟悉許多儀器未被廣泛應用前的觸診的技術，而醫生的這些動作，不單單只是從我身上獲取醫療的資訊，從我的角度來說，那是一種關愛，一種治療的動作，然而，最特別的是他最後放下所有手上的東西，專注的看著我而說的那些話時的整個動作，那彷彿在告訴我，別擔心，我還有許多法寶，這次就讓我們用用「點滴」這個法寶來幫助你吧。他的專注和信心，真的讓我很快就從原本病懨懨中健復了過來，僅管，我知道點滴不過就是生理食鹽水罷了。

   說到這裡，藥物和治療手段是什麼，彷彿就不是那麼重要了，它可以是各種東西，如草藥、按摩、針炙、食物、藝術…等，甚至是毒藥，但重要的是被端到台面上的這個東西，在全語言裡所代表的意義是什麼，在患者主觀整體的詮釋又是什麼，才是真正的重點。然而，即使是如此，還有許多東西更值得探討，因為在溝通的過程，有時，人們會因此得到療癒，而有時則會陷入悲慘的絕境，而有時，這種溝通，卻可能為人打開新的人生觀，創造新的方法來認識世界、認識自己，並開創自己新的生命，而這卻是許多無解的絕症，最佳的的良藥。就我所知，替代療法真正的價值就在這個地方。

   我想多談談醫師或神職人員所扮演的角色，這樣子的醫治者，他們通常擁有一種權威性的象徵，他們所做的一切，對病人有著十足的影響力，有時，光是他們的身份，就能帶來莫大的療效。愛彌爾．庫埃[fn:9]曾說，「醫師光是自己的頭銜就能對患者產生巨大影響。」這確實一點也沒有錯。

   在原始點訪問的期間，我記下了一個故事，或許非常適合放在這一個章節中來思考，由於原始點療法主要依靠的是一種按摩的技術，因此，按摩就成了治療者和患者間最主要溝通的工具，一次，一位資深的志工來找張釗漢醫師，說有個患者的狀況，無法用按推為他帶來緩解，想問問張醫師的看法，張醫師聽了之後，就親自過去為那個人按推，神奇的是，按推沒有幾下，病人的症狀就得到極大的改善。後來，他們內部開會討論這一類按推無效的案例，他們得到的結論是，「手法不夠到位，學無止盡，在手法上得不斷的精進。」從原始點醫療的世界觀出發，那確實是一條看起來頗為合理的解釋，但他們卻都完全忽略了張釗漢醫師本身的象徵所帶來的象徵意義，我想，如果當時不是張醫師這一按，這個難解的症狀，就算用盡手法，可能也不會有這麼戲劇化的改變。

   另一個例子藉由醫生的引導而走向療癒之路的，是一位卵巢癌末期的患者，她說，
   #+BEGIN_QUOTE
   在我做完放化療之後，我的醫生和我說了一句話，這句話永遠在我的心裡影響著我，他說，『醫療已經告一個段落了，接下來你得靠自療。』那句話，真正的帶領我走向康復的道路，一開始，他拿了一些氣功的資訊給我，希望我能去練習，但我都沒有興趣，直到有一次，他拿出了一個關於瑜伽和呼吸法練習的簡介，才真的打動了我，因為小年輕的時候，就一直想要做瑜伽，所以我就去了，然而，在做完第一次之後，由於身體太過勞累，所以我並沒有持續的練習。在一次的回診，他問我，「有繼續去參加團體練習嗎？」我回答他沒有，他卻說，「不然這樣子好了，你到我家附近的這個練習場來，我陪你練習。」我聽完這段話，大受感動，也就答應了。到了這個團練場後，僅管身體非常的不舒服，但看到醫生也在旁邊陪我練習，就讓我無比的感動，因此，我就如此持續不斷的練習下去了。
   #+END_QUOTE


** 再論原始點
#+BEGIN_EXPORT html
<a id="org002"></a>
#+END_EXPORT

   從原始點的思想架構來看，我們的身體，好像藏著一些重大的開關，這些開關，直接控制了所有症狀的發生，也因此，想要緩解身體的所有症狀，就得從這些開關來下手，這些藏在身體各懂的重要開關，就稱之為原始點。所有的疾病，其因不出有二，一者熱能不足，二者體傷。體傷會損一個人的熱能，而熱能不足也會反過來造成體傷。一但熱體低到一個程度，人的體力也就跟著喪失，人的體力喪失後，死亡就不遠了，因此，判斷一個人是否還有康復希望的關鍵指標就是一個人的體力，只要有體力，一切都還有希望。熱能，是一個抽象的概念，它是一個依附著我們的感覺而建立起來的概念，並不是現代科學所說的熱，也稍稍不同於古中醫寒涼的準則，簡單說，熱能，其實就是生命的能源，只要有熱，身體的器官就有足夠的能量來運作，而我們的身體就會感覺到暖和，肢體才能正常的伸展，不會緊繃，心情才能平順。所以，對一個病人來說，維持熱能就是很重要的一個因素，因此，原始點希望那些重症的患者，都要注意保緩，維持溫敷，以自己的身體感到暖和為原則，利用這種外熱能的補充，可以減少病人熱能的損耗。另一方面，原始點也極度的重視飲食，飲食會直接影響到我們的內熱源，溫熱的飲食，可以補充一個人的熱能，而寒涼的飲食，則會損耗，而薑正是補充熱能最佳的食品，因此，薑湯的飲用，就成了原始點非常重視的一個環節，他和溫敷的應用，成為原始點醫療在治療病痛時，最重要的內熱源和外熱源。

   體傷，是因為不當的使用身體，常年累積而造成的傷害，體傷會影響各個器官的運作，而在身體上表現出各種的症狀。如果症狀出現的地方，並不是落於原始點之上，這種狀況的體傷，稱為他處體傷，可以透過相對應的原始點上的按推來得到緩解。若是症症狀出現的地方，剛好就落在原始點之上，這種狀況的體傷，就被稱為本處體傷，本處體傷無法透過按推來緩解，只有靠著內外熱源的補充，才有辦法慢慢的得到改善

   也因此，對於重症的患者(幾乎二十四小時都處於不舒服的狀態)，一定要要從五個環節下手，才有可能走向自癒之路，這五個環節分別是，心情的調適、足夠的運動、溫熱的飲食、溫敷、和按推。其中，要做到心情的調適，就必須對疾病有正確的認識，錯誤的認知帶來不必要的恐懼，恐懼會耗散人的熱能，所以要除去恐懼，就得擁有正確的知識，所以原始點醫學，非常希望患者能夠深入的了解原始點的知識，意圖打破病人內在的恐懼以建立起對身體的信心。而適當的運動，則會促進身體機能的運作，協助身體補充熱能，並去除身體不當使用所累積的體傷。溫熱的飲食和溫敷，就是借用內外熱源，來補充身體的熱能，以加速身體的回復。按推，則是解除症狀最重要的一項技術，只要按推得當，身體的傷傷就可以被人以外力給化解，症狀自然就會解除。

   這套醫學理原，看起來並不十分複雜，可以很容易的被人所理解，加上案例的演示，這套療法就很容易成為一個強而有力的聲明，在某種程度上，這套學說，對人類的身體運作，已經建立起一個小型的世界觀，我不太確順著它走會發展到什麼地步，但確實有許多的人受到這套療法的影響，而走向康復的道路。曾有個受訪的朋友和我說，在得了癌症後，因為心靈上的成長，他已經看透生死，不在害怕死亡，然而，對於症狀的煩惱與恐懼，卻始終跟著他，直到他認識了原始點療法之後，這個恐懼就慢慢消失了。此外，我還得談談原始點醫學另外的一些面向，這些面向，並不在他們自己的理論當中，卻在實踐之中被體現出來，原始點本身是一個公益團體，有很多的志工在其中幫忙，也有許多人，是從主流醫學的絕症中走出來的人，某種程度，它提供了一股慈悲的情懷，也延續了許多宗教中無私利他的理念，關於這點，我們可以從等一下的案例中，充分的看到這個面向。

   張醫師常常在演講上說，「既然你們會找上我，大概已經是走頭無路了，既然都走頭無路了，就信我這一回吧。」雖然這話語帶玩笑，但在這個醫學架構之下，癌症並不是什麼不治之症，它確實給許多人，特別是資源相對貧乏的人，帶來無比的希望。

   #+BEGIN_QUOTE
      2010 年，七月中旬，因為排便不順，有血絲，在家人的鼓勵之下，檢查出大腸癌三期。於是就轉到內湖三軍總醫院做了進一步的治療，因為腫瘤長在直腸靠近腔門 7~8 公分的地方，建議先做放化療，再來開刀。療程結束後，腫瘤控制住了，但仍需每個星期去回診做檢查。當時，我的身體非常的虛弱，味覺都被破壞了，整個屁股由紅變默，很痛，有灼熱感，坐也不是躺也不是，很辛苦，只能坐在游泳圈之上，加上那時身體很怕冷，所以每次的檢查都很痛苦，回來都得休息個好幾天，食癒也愈來愈差，體重從 58 公斤廋到 45 公斤。腳變的非常彊硬，走路無法不平衡，腳踝沒有辦法，腰的活動度也降低了很多。
         後來，我知道了原始點基金會，就到原始點咨詢，整個人突然感受到無比的希望，張釗漢醫師的建議，「爬山，一次兩階、按推、溫敷、喝薑湯、不吃寒涼的食物、維持平穩的心情，我通通都接受了，很快，大概一個月後，體力就回復了。」 有體力之後，我就開始就開始到基金會學習按推的手法，想要幫助那些和我一樣受苦的病人。所以從那時起，我就每天到基金會當義工。西醫處理過後，腫瘤雖然控制住了，但身體卻更差了，因此，在接受了張醫師的醫療理念後，我就不再去醫院做檢查，只要有體力，生命就還有希望，症狀就利用按推、溫敷、薑湯和運動來處理就行了。經過了一年的調理，體重和體力也回復了。好吃，好睡。因為又想幫助別人，所以煩惱愈來愈少，成長受益非常多。
         剛到原始點復健之後，大約兩個星期，我發現排便中帶著血，但我相信原始點的理論，所以沒有回醫院檢查，加強薑湯的濃度，也加強運動，之後狀況就消失了。此後，我對原始點的理論，就更有信心了。七八個月之後，出現帶狀泡診。我自己反省，認為是太過勞累造成的，所以就向基金請假休息。三天後就完全回復了。以前三十幾歲時，我也得過一次，那次用了各種的療法，耗了一個多月，才開始有些許的好轉，而這次竟然三天就好了。所以這又讓我進一步更相信原始點療法。也開始了解到，為何原始點會說，雖要運動，不可過度勞累。親身的經歷是檢驗真理的最好的方法，當你試過之後，感受到甜頭，你就會相信，並持續的做下去了。
         生病之後，人生觀改變了非常得多，一開始的生活，是以益字為準則，沒運動，飲食不正常，每天都喝大量的烏龍茶，吃寒涼的水果，工作時間長，經營的壓力很大，身心疲累。生病之後，立刻把工作收起來。損失很大。可是，現在的我，開始以付出為主，不在以利為標準。以前雖然賺很多錢，心裡總覺得錢怎麼都不夠用，心裡其實很匱乏，整天擔心受怕，反到是現在都在幫助別人，反而感到富足，因為自己有能力，才讓我更能去幫助別人。
         生病對我自己來說，是上天賜給我的福報，讓我有機會遇到原始點，幫助別人，不然我可能還在紙醉金迷。現在，自我縮小了，傲慢少了。以前的生活，利字當頭，表面上是朋友，私底下各懷鬼胎，反而現在的生活，自我小了，沒有憂慮，更加的自在。
   #+END_QUOTE


** 療癒是世界觀的拓展與改變
#+BEGIN_EXPORT html
<a id="org003"></a>
#+END_EXPORT

   再一次，我們把主題回到癌症的療癒之上，或許，我已經不太喜歡用癌症來稱呼這些在受苦的人們，因為它的包袱真的太大了，在台灣，癌症兩個字，幾乎就是死亡等義詞，也是所有痛苦的檢查和治療的開始，得了癌症，不經過個五年十載，是沒有辦法從這個病症的印記中解脫，就算放療化療控制住了病情，每三個月的回診，就像玩了一次抽鬼牌的遊戲一樣，萬一不幸二度復發，那真的是叫天天不應，叫地地不靈了。那麼，到底該怎麼從癌症這一類的絕症之中康復呢？答案就是，不論用什麼樣的方法，去擴展甚至是改變自己的世界觀，這個世界觀，可以是自己去創造的，也可以是一個團體、上師或醫生所付與的，也可能藏在一個未發展的天賦裡，世界有多大，生命就有多少可能。

   #+BEGIN_QUOTE
   許媽媽，二十年前被診斷出癌症，那為他和他家人的生命，開了一道新的大門。在生病的期眼，一個朋友拿了李秋涼小姐推廣的生機飲食的資料來給他，他看了之後，決定去現場看看怎麼一回事，當他聽完演講後，心裡突然閃出一個直覺，「這正是我所需要的東西啊。」從那時開始，他們從家投入了生機飲食的行列，先生甚至研究起有機栽種的各種技術，並成為講師四處演講，並在家裡的庭園，種起了有機的食物，親自為家裡的人烹煮。而許媽媽自己，則是發展出極為敏感的感官能力，不只是味覺，連嗅覺都可以聞出這個食物對自己是好還是不好。透過傾聽自己身體的反應，身體回復了健康，至今已二十多年了，目前的她，每天早上都會到附近的公園練氣功，游泳，身體十分的健康。
   #+END_QUOTE

   #+BEGIN_QUOTE
   高遠智子，日本北海道人，在 1997 年 28 歲之時，被診斷出卵巢癌第三期，壽命只剩半年，但經過手術、放療、化療，竟然奇蹟的活了三年，這從主流醫學的角度來說，已經算是奇蹟了，但此時，真正的惡夢才真正開始，癌細胞轉移到肺臟，而全身也因為放化療產生各種的後遺症，包括失去味覺。智子知道自己的生命已經走到盡頭，他拒絕了安寧治療，想要為自己做些有意義的事，讓自己了無遺憾的走完人生。因為智子的父親，在她 18 歲時，就得了肺癌過世，而他爸爸曾告訴她，如果病好了，一定帶她去法國看莫內的名畫，這個願望，當然沒有實現，而智子想要親自去完成這個願望。然而，智子的身體極差，航空公司不願讓他上飛機，但在他百般要求之下，他順利成行。在法國的時候，他為了不造成同行的人的負擔，幾乎都待在飯店裡休息，一有體力，就到美術館去看莫內的睡蓮，這讓她心滿意足。一次，同伴提議一同去蒙馬特山丘，智子開始咳嗽，法國空氣乾燥，更讓他口乾舌燥，她身上的水已經喝完，這讓她想哭都哭不出來，同伴幫她找水，卻都找不到買水的店，只看到擺在店鋪門前，擺放著她從小就最討厭的蕃茄。大家勸她吃，她覺得厭煩，想不到在她病到這種程度的時候，她居然還得去吃最討厭的蕃茄。智子試著讓自己靜下，她想了想，反正自己都已經失去味覺和嗅覺了，就算再討厭吃的東西，也不會有味道，那何不試試看呢？她慢慢的咬了一小口。哇，不可思議。已經失去味覺的人，居然從舌根處湧出唾液，而且還愈來愈多，一時激動，連乾澀的眼睛也泌出淚水。最神奇的是，知子漸漸地感覺到甜味，失去的味覺一瞬間竟然恢復了，喉嚨深處也感受到酸味，她激動的乾淚，真的好好吃，為什麼自己從來不知道番茄這麼美味，分泌超多的唾液。怎麼會這樣？這讓智子好感動。從小就不注重飲食的智子，在這一刻有了全新的經驗和感受，她開始思索，當食物、身體和心靈合而為一，就算是像自己這樣子孱弱的身體，也能夠感受到病痛的疏緩。這才是飲食的真義吧。而後，她拖著病體，到法國學習廚藝，並拿到芳療師執照，最後她又跑到中國，學習中國的藥膳，並取得中醫藥膳師資格，此時的她，癌症早就消失的無影無蹤，她開始教導大家，如何利用食物來治療自己的各種疾病[fn:10]。
   #+END_QUOTE

   這是兩個食療成功的例子，非常值得人們一看再看，我的描述非常的簡單，因為，重點並不是吃了什麼食物，而是食物為人們帶來何種精神上的感動與與生活上改變，現在市面上食療的書很多，很多人看到，都是立刻去翻相對應的病症，像是在找仙丹一樣，看看能不能藥到病除，然而結果總是令人失望的。人們常常只能看到表面的現象而忘了精神上的感動。有時，這種精神上的觸動而引起的改變，是來自於一個世界觀與自己絕然不同的團體，所以，我想摘錄兩則氣功療癒的故事。

   第一個例子：
   #+BEGIN_QUOTE
      幾年來，靠著年輕力壯，全心全意拼命於工作，事業上，一天工作13個小時乃家常便飯，偶爾再上個夜班，更不以為意。 首先，一定要感謝老天爺讓我得了癌症，若不是如此安排，我也不知道人生中，除了工作，原來還有更多可利益眾生之事。 「上天為你關上一道門，必也為你開啟另一扇窗。」我深刻地體悟了。回想罹患鼻咽癌至今，已過了兩年多了，醫生告知診斷報告時，是呆了？還是心已有預期了？我竟然出奇平靜地接受它的存在，沒吶喊，不怨天尤人。經歷化療和 36 次電療的西醫療中，感染高燒，聲帶受損，插鼻胃管進食，短短兩個月，體重由 67kg 突然降到 50kg，如此折磨下，家人的親情一直是支撐著我最大的力量：媽媽天天熬粥，爸爸不厭其煩地一次次用果汁機攪爛泥粥，慢慢地、緩緩地，那份愛就順著鼻胃管送進了虛弱的身體中。 我的勇敢獲得老天爺的厚愛，約莫半年後，在學校舉辦的講座中，認識了路竹練功場的錦慧師姐，在她多次的鼓勵邀約下，終於決心拼棄無法早起的惰性，開始接觸「返老還童功法」，至今也快兩年了。 在電療時因喉嚨受損，唾液亦無法正常分泌，剛開始練功時根本無法言語，感謝素玉教練的指導，感謝素蓮教練給我機會，我嘗試背口訣帶功，從第一式到第五式，再漸進第六式到第十二式、氣功跑步，甚至帶小抄帶靜氣功；每天用心地實踐著，從帶功中我重拾信心，去年底的單車行挑戰一日雙塔，24 小時內完成石門富貴角燈塔和墾丁鵝鑾鼻燈塔，驗證了我病後的體力。一年多來，每天從岡山到路竹，我力求每一式功法都要做到位，要強壯身體遠離死神召喚。今年七月在世通總監的鼓勵下，到了阿蓮國小開新場，每天 20 分鐘的車程，我卻甘之如飴，只期待著「返老還童」能造福更多有緣的師兄姐。 生死關前的徘迴，工作、家庭、健康，孰輕孰重？我已經將它重新洗牌了。當健康發出了警訊，往往再多的財富也喚不回當初，唯有擁有健康，人生的艷麗色彩，才能揮灑自如[fn:11]。
   #+END_QUOTE

   另一個例子：
   #+BEGIN_QUOTE
   自幼在農村長大，從小練就一副好身體，結婚後從事土地整合開發事務，工作時間自由，沒有很大的壓力，所以身體也一向硬朗，少有病痛。民國100年11月，吃了午餐後，突然感到肚子有些疼痛，熟知越來越痛，便到床上躺，躺了兩個多小時更覺疼痛，我太太催促我趕快就醫。 在急診室診斷之後，隔日照大腸鏡，最後竟診斷出是大腸癌第三期，有如晴天霹霹，久久無法自己。這是我有健保卡以來，第一次掛號看診，我的健保卡被註記著「重大病患」，不看診則已，一看卻是重大疾病，令人難以置信。 聖嚴法師說，「處事四態度：面對它，接受它，處理它，放下它。」既然發現是癌症，也只有聽從醫師指示，開刀、做化療。我知道化療會引起引多後遺症，心裡其實頗為排斥。 初期住院期間，同為大腸癌，同一主治醫師的鄰床病患，已經進行第二次化療療程，但他身體每況愈下，做第九次化療時，癌細胞已經轉移到肝臟，他請教主治大夫，「若繼續化療，我的腫瘤保證會消失嗎？」醫生並未做出承諾，只強調化療十二次的標準流程要做完，當下我決定不再繼續做化療。不做化療不是就等此等死，我看了很多書，也到台中看出書分享抗癌經驗的腦神經外科名醫許達夫，也有關心的朋友提供偏方，但一直沒有找到我要的答案。 直到有一天，我生命中的貴人出現了，癌友陳正山突然打電話給我，說他妹妹約他清晨五點半在台南仁德運動公園練氣功，也約我一起去，當天我認識了沈世通教練，這是我與反老還童氣功第一次接觸。 在教練的鼓舞及指導下，我開始在歸仁紅瓦厝練功場修煉返老還童氣功，練了二十多天，便參加協會舉辦的 CAM 癌症輔助療法三天兩夜課程，在專業醫生指導下，我找到了生活的方向，改變了內心的追求，學會如何放下，我知道我要健康，就要改變我自己。 隨後，又參加基礎訓練班，知道返老還童功每一個動作對人體健康的影響，在修練功法時，更為到位。 秉持追求健康的信念，我用心練功，練功場是我每天必報到的地方，練功成為我每天最重要的工作。加上飲食、生活作息的調整，覺得自己的身體愈來愈輕鬆，也特別想到自己是癌症病人，朋友看到我總是說，「啊，你的氣色那麼好，根本就不像是癌症病人。」我聽了自然很開心，知道那些壞的癌細胞已被我趕走大半。 上課時，蔡老師曾說，勤練三個月會有好的反應，勤練三年會改變體質。我持續三個月練功之後，一些小毛病像是鼻子過敏，鼻涕倒流的症狀不知不覺不見了，到醫院回診，腫瘤標記 (CA-199) > 37 ，我的結果值 6.2 ，癌胚胎抗原 < 5 ，醫生說我保養的很好，要我繼續下去。我的身體愈來愈輕鬆，健康也展現在每天的笑臉上。 從三年半前因大腸癌接觸返老還童氣功迄今，我幾乎從未間斷練功，也要求自己每個動作都要「到位」，將近四年練功最大的成果及最令我開心的事，是我的癌細胞指數已經完全消失，這幾年的努力讓我 重拾健康，生命重現光彩。如今我當然更珍惜這份機緣，一輩子練功[fn:12]。
   #+END_QUOTE

   我還不想深入的討論氣功的許多面向，僅僅只是想讓大家看到，不同的世界觀開創出新的世界，如何為人們帶來生命的希望與轉折。有時，光是去發展一個天賦，都可能帶來不可思議的改變。
   下面這個例子，是一位中國大陸的微雕藝術家張翼的故事：
   #+BEGIN_QUOTE
   1999年，張翼 36 歲，卻被醫院檢查出直腸癌，在家人的堅持下，他開刀拿掉了自己的直腸和膀胱，手術暫時控制住了他的病情，然而，好景不常，八個月後，癌症復發了，這一次就不像上一次這麼幸運，醫生認為，最多不過只能活兩個月。 當時，他心灰意冷，決定放棄治療，甚至想要自殺，在自殺失敗後，他想起了一個從前在村子裡親身經歷到的一個故事，有個老翁，因為肺結核而病的奄奄一息，眼看就要斷氣了，他的兒子，急忙帶著他去醫院，醫院檢查之後，發現竟是誤診，老翁一聽，心情一好，病症居然完全消失了。這個故事似乎在告訴他，人的注意力是可以轉移的，只要我能夠轉移我的注意力，只要不要在疼了，活兩個月也行。為了解決身體巨大的疼痛，他決定找一個需要高度集中精神的工作來做，這時他想起他在年輕時，曾經認識一個做微雕老師，熱愛書法的他，立刻對微雕產生無比的興趣。張翼心想，那就利用微雕來轉移自己的注意力吧，他開始刻一些章，但總覺得文章太短，無法一直維持專注來減輕自己的疼痛，所以最後他選了紅樓夢來刻，刻啊刻的，疼痛也真的慢慢減輕了，一個月過去了，兩個月過去了，張翼還活著，一年、兩年、三年，他終於把紅樓夢給刻完了，奇蹟的是，他的癌症也完全的康復了[fn:13]。
   #+END_QUOTE

   另一個例子，是中國大陸灰學的創始人孫萬鵬，
   #+BEGIN_QUOTE
   1988 年的 9 月，孫萬鵬被醫院診斷出而且已是晚期，一時，無邊的痛苦襲上心頭，癌症，這個惡魔，為什麼對他一家這樣窮追不捨？一年前，他妹妹得癌症去世，癌症部位與他的部位完全相同，而他的父母也都是死於癌症。現在，這個惡魔又向他張開了血盆大口……還有一年時間，這是醫生的判斷。 一切都完了，殘酷的現實赤裸裸地呈現在他面前，等死嗎？或是還能做些什麼呢？他想到了灰色系統，於是全心投入寫作。他要她的妻子準備幾件東西：一條燈籠褲，寫作時穿，以便身體不適時馬上可以盤腿做氣功，10盒清涼油和2斤幹辣椒，用於疲勞時提神，幾筒蠟燭，以備停電時不影響寫作，一個小鬧鐘，可為他作叫醒服務，幾支耳針，瞌睡時可扎一下。於是，他便全神貫注的投入灰學的研究與寫作。幾乎每次寫作時，他都要擦清涼油提神，如果還不夠刺激，就嚼一個幹辣椒，直辣得頭上冒汗為止。寫作的進度毫無規律，完全視身體狀況而定。有時半夜感到身體舒適一點，他馬上起來寫作，幾乎已到了完全忘我的地步。7 月23 日凌晨，孫萬鵬在稿紙上寫下了最後一行文字。第一部灰學專著，24 萬字的「表現學」終於完成了。在此後的九個月中，孫萬鵬又接連完成了「灰色價值學」，「調查學」兩本專著。 1993 年，孫萬鵬的身體發生了奇妙的變化。他的身體裡的生命抗體日益強盛，肝部的疼痛緩解了，精神也好起來，後來檢查發現，他身上的癌細胞已完全消失了[fn:14]。
   #+END_QUOTE

   有時，新的世界觀，也會來自於一個內在極度景仰的人，例如一位宗教的上師，
   #+BEGIN_QUOTE
   陳小姐，台灣國際生活的藝術中心資深講師，曾是台灣 20 年來賣汽車的頂尖銷售員，月入百萬，又是第一位把丹尼爾電腦辭典萊思康引進香港，在商場打過不少大小勝利的戰役的女強人。但是生命無常，正值事業高峰的她，卻發現罹患了乳癌，醫生要她立即開刀、放療、化療，否則活不過半年。她聽到醫生的宣判後，心裡非常的困擾，她並不想要做這樣子的治療，於是，他坐了一趟飛機，前往印度去見他的上師Sri Sri Ravi Shankar[fn:15]，向他的上師求救，他的上師看到她之後，只對她說了一句話，「回去教大家我教你們的東西。」她聽了之後非常的驚恐，心想，我都得了癌症了，竟然還能做這樣子的事，於是她回國之後，就開始在台灣、香港和馬來西亞教授大家這套由印度生活的藝術發展出來的淨化呼吸法，他自己不但從癌症中康復，也幫助了許多生病中的人。
   #+END_QUOTE

* Footnotes

[fn:1] https://en.wikipedia.org/wiki/Ramakrishna

[fn:2] https://en.wikipedia.org/wiki/Teresa_of_Ávila

[fn:3] https://en.wikipedia.org/wiki/Francis_of_Assisi

[fn:4] https://en.wikipedia.org/wiki/George_Fox

[fn:5] https://en.wikipedia.org/wiki/Thomas_Carlylexs

[fn:6] 威廉．詹姆士，《宗教經驗之種種》，立緒文化，2001，頁12

[fn:7] Hinman RS, McCrory P, Pirotta M, et al. Acupuncture for chronic knee pain: a randomized clinical trial. JAMA 2014;312:1313–22.

[fn:8] 道教信仰中的神祉，見：https://zh.wikipedia.org/wiki/王爺千歲信仰

[fn:9] https://en.wikipedia.org/wiki/Émile_Coué

[fn:10] 高遠智子，《領悟食物的力量，我從末期癌症重生》，如何，2015

[fn:11] 蔡良安，《返老還童雙月刊》，中華潛能心理學會，第四十二期，頁14

[fn:12] 蔡良安，《返老還童雙月刊》，中華潛能心理學會，第四十三期，頁18

[fn:13] http://www.chinaonco.net/Article/ShowArticle.asp?ArticleID=2115

[fn:14] http://www.baike.com/wiki/孙万鹏

[fn:15] https://en.wikipedia.org/wiki/Ravi_Shankar_(spiritual_leader)
